version: '3.8'

services:
  gerenciamento:
    build: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "5001:5000"
    volumes:
      - ./gerenciamento/database.db:/app/database.db