version: '3.8'

services:
  gerenciamento:
    build: ./gerenciamento
    container_name: gerenciamento
    ports:
      - "5001:5000"
    volumes:
      - ./gerenciamento/database.db:/app/database.db
    networks:
      - rede_escola
  
  reservas:
    build: ./reservas
    container_name: reservas
    ports:
      - "5002:5000"
    volumes:
      - ./reservas/reservas.db:/app/reservas.db
    environment:
      - SERVICO_GERENCIAMENTO_URL=http://gerenciamento:5000
    depends_on:
      - gerenciamento
    networks:
      - rede_escola

  atividades:
    build: ./atividades
    container_name: atividades
    ports:
      - "5003:5000" # Expõe na porta 5003 do host
    volumes:
      # O config.py de atividades usa 'atividades.db'
      - ./atividades/atividades.db:/app/atividades.db 
    environment:
      # Também precisa de comunicar com o gerenciamento
      - SERVICO_GERENCIAMENTO_URL=http://gerenciamento:5000 
    depends_on:
      - gerenciamento # Depende do gerenciamento para estar online
    networks:
      - rede_escola

networks:
  rede_escola:
    driver: bridge